deploy:
  branch:
    server: krypton.vps-private.net
    username: mv
    dir: '{home}/github/{repo_owner}/{repo_name}/branch/{branch}'
    env_vars:
      docroot: '{home}/domains/mv.krypton2.vps-private.net'
      domain: 'mv.krypton2.vps-private.net'
      database_name: mv_main
      database_user: mv_main
      database_pass: main
      account_user: admin
      account_mail: bober2000@ukr.net
      account_pass: dbnfkbq
      site_mail: no@mail.net
      site_name: test-site-d8
      default_theme: "bartik"
      enable_devel: "yes"
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'

